// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Jest             = require("bs-jest/lib/js/src/jest.js");
var Curry            = require("bs-platform/lib/js/curry.js");
var ApplicativeMonad = require("../re/applicativeMonad.js");

describe("ApplicativeMonad", (function () {
        var id = function (x) {
          return x;
        };
        var add = function (x, y) {
          return x + y | 0;
        };
        Jest.test("return", (function () {
                return Jest.Expect[/* toEqual */11](/* T */[3])(Jest.Expect[/* expect */0](ApplicativeMonad.$$return(3)));
              }));
        Jest.test("bind", (function () {
                var m = /* T */[id];
                return Jest.Expect[/* toBe */1](5)(Jest.Expect[/* expect */0](Curry._1(ApplicativeMonad.bind(m, id), 5)));
              }));
        return Jest.test("apply", (function () {
                      var m = /* T */[add];
                      var m1 = ApplicativeMonad.apply(m, /* T */[1]);
                      var m2 = ApplicativeMonad.apply(m1, /* T */[2]);
                      return Jest.Expect[/* toBe */1](3)(Jest.Expect[/* expect */0](ApplicativeMonad.bind(m2, id)));
                    }));
      }));

/*  Not a pure module */
