// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';


function push(screen) {
  return /* PushScreen */[screen];
}

function pop() {
  return /* PopScreen */0;
}

exports.push = push;
exports.pop  = pop;
/* No side effect */
