// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function apply(param, param$1) {
  return /* T */[Curry._1(param[0], param$1[0])];
}

function bind(param, f) {
  return Curry._1(f, param[0]);
}

function $$return(a) {
  return /* T */[a];
}

var $less$dot$great = apply;

var $great$great$eq = bind;

var pure = $$return;

exports.apply           = apply;
exports.$less$dot$great = $less$dot$great;
exports.bind            = bind;
exports.$great$great$eq = $great$great$eq;
exports.$$return        = $$return;
exports.pure            = pure;
/* No side effect */
