// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry            = require("bs-platform/lib/js/curry.js");
var ApplicativeMonad = require("./applicativeMonad.js");

function make(update, f) {
  return /* Event */[
          update,
          /* T */[f]
        ];
}

function popEvent(param) {
  Curry._1(ApplicativeMonad.bind(param[1], param[0]), /* () */0);
  return /* () */0;
}

function apply(param, b) {
  return /* Event */[
          param[0],
          ApplicativeMonad.apply(param[1], b)
        ];
}

function mApply(param, b) {
  return /* Event */[
          param[0],
          ApplicativeMonad.apply(param[1], /* T */[b])
        ];
}

function bind(param, f) {
  return ApplicativeMonad.bind(param[1], f);
}

var $less$dot$great = apply;

var $less$dot$dot$great = mApply;

var $great$great$eq = bind;

exports.make                = make;
exports.popEvent            = popEvent;
exports.apply               = apply;
exports.$less$dot$great     = $less$dot$great;
exports.mApply              = mApply;
exports.$less$dot$dot$great = $less$dot$dot$great;
exports.bind                = bind;
exports.$great$great$eq     = $great$great$eq;
/* No side effect */
