// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj       = require("bs-platform/lib/js/caml_obj.js");
var StackNavigator = require("reason-react-native-navigation/lib/js/src/stackNavigator.js");

function compare(a, b) {
  if (typeof a === "number") {
    if (a) {
      if (typeof b === "number" && b !== 0) {
        return /* true */1;
      } else {
        return /* false */0;
      }
    } else if (typeof b === "number" && b === 0) {
      return /* true */1;
    } else {
      return /* false */0;
    }
  } else if (a.tag) {
    if (typeof b === "number" || b.tag !== 1) {
      return /* false */0;
    } else {
      return Caml_obj.caml_equal(a[0], b[0]);
    }
  } else if (typeof b === "number" || b.tag) {
    return /* false */0;
  } else {
    return Caml_obj.caml_equal(a[0], b[0]);
  }
}

var Navigator = StackNavigator.Make(/* module */[/* compare */compare]);

exports.compare   = compare;
exports.Navigator = Navigator;
/* Navigator Not a pure module */
