// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry              = require("bs-platform/lib/js/curry.js");
var Utils              = require("./utils.js");
var TextRe             = require("bs-react-native/lib/js/src/components/textRe.js");
var ReactNative        = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
var TouchableOpacityRe = require("bs-react-native/lib/js/src/components/touchableOpacityRe.js");

var component = ReasonReact.statelessComponent("TaskView");

function make(task, onEdit, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* array */[
                        ReasonReact.element(/* None */0, /* None */0, TextRe.Text[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[Utils.str(task[/* title */1])])),
                        ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onEdit], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, TextRe.Text[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[Utils.str("Edit")]))]))
                      ]
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
