// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var StyleRe     = require("bs-react-native/lib/js/src/styleRe.js");
var TaskItem    = require("./taskItem.js");
var ReactNative = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("TaskList");

function make(tasks, onPress, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var taskItem = function (task) {
        return ReasonReact.element(/* Some */[task[/* id */0]], /* None */0, TaskItem.make(onPress, task, /* array */[]));
      };
      var taskList = $$Array.of_list(List.map(taskItem, tasks));
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[StyleRe.style(/* :: */[
                              StyleRe.flex(1),
                              /* :: */[
                                StyleRe.justifyContent(/* center */98248149),
                                /* :: */[
                                  StyleRe.alignItems(/* center */98248149),
                                  /* [] */0
                                ]
                              ]
                            ])],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* array */[taskList]
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
