// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Utils              = require("./utils.js");
var TextRe             = require("bs-react-native/lib/js/src/components/textRe.js");
var BubbleEvent        = require("./bubbleEvent.js");
var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
var TouchableOpacityRe = require("bs-react-native/lib/js/src/components/touchableOpacityRe.js");

var component = ReasonReact.statelessComponent("TaskItem");

function make(onPress, task, _) {
  var handlePress = function () {
    return BubbleEvent.popEvent(BubbleEvent.$less$dot$dot$great(onPress, task[/* id */0]));
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[handlePress], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, TextRe.Text[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[Utils.str(task[/* title */1])]))]));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
