// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function str(prim) {
  return prim;
}

function apply(param, param$1) {
  return /* T */[Curry._1(param[0], param$1[0])];
}

function bind(param, f) {
  return Curry._1(f, param[0]);
}

function $$return(a) {
  return /* T */[a];
}

var ApplicativeMonad = /* module */[
  /* apply */apply,
  /* <.> */apply,
  /* bind */bind,
  /* >>= */bind,
  /* return */$$return,
  /* pure */$$return
];

function popEvent(param) {
  Curry._1(param[0], param[1][0]);
  return /* () */0;
}

function apply$1(param, b) {
  return /* Event */[
          param[0],
          apply(param[1], b)
        ];
}

function mapApply(param, b) {
  return /* Event */[
          param[0],
          apply(param[1], /* T */[b])
        ];
}

function bind$1(param, f) {
  return Curry._1(f, param[1][0]);
}

var BubbleEvent = /* module */[
  /* popEvent */popEvent,
  /* apply */apply$1,
  /* <.> */apply$1,
  /* mapApply */mapApply,
  /* <..> */mapApply,
  /* bind */bind$1,
  /* >>= */bind$1
];

exports.str              = str;
exports.ApplicativeMonad = ApplicativeMonad;
exports.BubbleEvent      = BubbleEvent;
/* No side effect */
